theme: jekyll-theme-minimal
title: Kurashicom Technology Group
description: About Kurashicom Technology Group
logo: https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2019-02-04/35cb76c1e1713890f1354417eec582cc.png
show_downloads: false
