theme: jekyll-theme-minimal
title: Kurashicom Technology Group
description: About Kurashicom Technology Group
logo: https://user-images.githubusercontent.com/29177665/50473881-1d578c80-0a02-11e9-8831-a35b32b1bec7.png
show_downloads: false
