theme: jekyll-theme-minimal
title: Kurashicom Technology Group
description: About Kurashicom Technology Group
logo: https://api.kurashicom.com/admin/dashboard/images/kurashicom-logo.png
show_downloads: false
